### ISSUE TITLE
Запрос /echo выдает мусор

### ISSUE THREAD

**Issue by vortigont** [DmytroKorniienko/FireLamp_JeeUI#3]
Иногда аякс запрос /echo выдает порченый джейсон. Ответ корректный по длинне, но часть данных либо забита одинаковыми байтами, либо кракозябрами. 
Проявляется это как залипший WebUI с надписью "обновить конфигурацию", на которую браузер не реагирует. Помогает либо перезагрузка контроллера, ли бо "затыкать" его запросами пока он сам не закрешится, натыкался уже несколько раз на это.
Тело ответа довольно большое, и судя по коду, оно формируется целиком в String'е.

https://github.com/DmytroKorniienko/FireLamp_JeeUI/blob/a42fe74964be506535cd6f7af2d18a3d5ed52492/lib/JeeUI2/JeeUI2.cpp#L153-L158

@DmytroKorniienko 
Вообще такое большое тело для экономии памяти кучи было бы лучше формировать динамически и выдавать клиенту чанками, а не целиком. Могу попробовать реализовать, например [как-нибудь так](https://github.com/vortigont/GyverLamp/blob/53fa7a5202a10183dbca519ebc75a528aabf34f6/gyverlamp/mqtt.ino#L252-L277) но пока не разобрался в JeeUI. Не смог найти в какой момент формируется String buf если в конце вызова server.on(PSTR("/echo") buf каждый раз очищается и что есть foo();?
JeeUI это вообще отдельный проект?

**Comment by DmytroKorniienko** [comment]
>>JeeUI это вообще отдельный проект?
Да, это отдельный проект, но автор его забросил, а я уже частично переписал.

foo - функтор конструирующий ответ echo по текущему интерфейс, фактически все из ui.cpp. Там все совсем грустно было по работе с памятью, чуть поправил, но не все. Если получится с чанками - то было бы замечательно.

**Comment by vortigont** [comment]
да, теперь нашел, спасибо. Гляну что можно сделать с минимальными изменениями

**Comment by vortigont** [comment]
Closed via #4

**Comment by vortigont** [comment]
Спасибо! фикс похоже реально работает,  у меня с большой матрицей очень часто бился этот /echo,  видимо памяти совсем маловато
