### ISSUE TITLE
Homepage not found

### ISSUE THREAD

**Issue by nicr4wks** [DmytroKorniienko/FireLamp_JeeUI#86]
Hello, is anyone able to help in english?

I have compiled and flashed the firmware to my NodeMCU but when i enter the URL http://192.168.4.1 I have the error 'Not Found'
![err1](https://user-images.githubusercontent.com/9098157/151337645-4175244e-2282-4581-8282-67f3daeb7a58.PNG)

I know the firmware upload has completed because I can view the config settings:
![err2](https://user-images.githubusercontent.com/9098157/151337880-5f974d58-3f8b-479d-98b4-c9fe3191de72.PNG)

Is there a different URL required to access the web interface?

Thanks.

**Comment by 80Stepko08** [comment]
You must upload file system for it.

**Comment by nicr4wks** [comment]
Thanks! that is working now.
I was trying to use google translate to follow the instructions but missed that part.
