### ISSUE TITLE
Війна.

### ISSUE THREAD

**Issue by kostyamat** [DmytroKorniienko/FireLamp_JeeUI#87]
Дмитро, з повагою до вас.
В зв'язку з ситуацією пропоную видалити російскомовний переклад, озвучку проекту. Перекласти опис українською, і розмістити банер англійською про війну.
Я розумію, що це нічого не міняє, нічим не допоможе, але як прояв протесту.

Чекаю на вашу відповідь. Як людина, яка, поки що, поза межами України, беру це на себе. Не буду вас, і інших відволікати. Але потрібна ваша згода.

Володя Lumenjer, та Стьопа stepko мене в цьому підтримують, ми всі на зв'язку. Якщо хочете, приєднуйтеся, можна мейлом, там сконтактуємося. Тримаймося, ми разом, все буде Україна! Слава Україні!

**Comment by DmytroKorniienko** [comment]
У мене на це немає часу, але ви якщо бажаєте, то зробіть.

**Comment by Lumenjer** [comment]
> У мене на це немає часу, але ви якщо бажаєте, то зробіть.
> 
> Героям слава!

Якщо потрібна якась допомога, ліжкомісця у Львові або Івано-Франківській області - пишіть
Мій телеграм https://t.me/Lumenjer

В любому випадку пишіть, будемо на зв'язку

**Comment by DmytroKorniienko** [comment]
Дякую хлопці, нажаль зараз є більш важливі справи ніж програмування. Та звісно  я залишаюсь там де моє місце.

Як буде вільна хвилинка - змерджу цю гілку до головної.

**Comment by 80Stepko08** [comment]
Було б ще чудово зв'язатись з вами. Якщо маєте Телеграм, зможете найти по цьому https://t.me/S_7_E_P_4_N
